# Generated by Django 4.2.5 on 2023-11-04 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_remove_shopuser_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopuser',
            name='age',
            field=models.PositiveIntegerField(default=18, verbose_name='возраст'),
            preserve_default=False,
        ),
    ]
