# Generated by Django 4.2.5 on 2023-10-17 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='наименование товара')),
                ('image', models.ImageField(blank=True, upload_to='product_images')),
                ('short_description', models.CharField(blank=True, max_length=32, verbose_name='краткое описание')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='стоимость')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_app.productcategory')),
            ],
        ),
    ]
