# Generated by Django 4.2.5 on 2023-10-17 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0003_product_brand_product_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='short_description',
        ),
        migrations.AddField(
            model_name='product',
            name='gender',
            field=models.CharField(choices=[('MALE', 'Муж'), ('FEMALE', 'Жен')], default='MALE', max_length=32, verbose_name='пол'),
        ),
    ]
