# Generated by Django 4.2.5 on 2023-10-20 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0004_remove_product_short_description_product_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, verbose_name='описание товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='gender',
            field=models.CharField(choices=[('MALE', 'Муж'), ('FEMALE', 'Жен'), ('UNISEX', 'Унисекс')], default='MALE', max_length=32, verbose_name='пол'),
        ),
    ]
